homepage:
    pattern: /
    defaults: { _controller: DTLTrainerBundle:Session:index }

session_new:
    pattern: /session/new
    defaults: { _controller: DTLTrainerBundle:Session:new }

sessions:
    pattern: /sessions
    defaults: { _controller: DTLTrainerBundle:Session:index, _format: html }

sessions_rss:
    pattern: /sessions/rss
    defaults: { _controller: DTLTrainerBundle:Session:index, _format: rss }

session_edit:
    pattern: /session/{session_id}/edit
    defaults: { _controller: DTLTrainerBundle:Session:edit }

session_view:
    pattern: /session/{session_id}
    defaults: { _controller: DTLTrainerBundle:Session:view }

session_delete:
    pattern: /session/{session_id}/delete
    defaults: { _controller: DTLTrainerBundle:Session:delete }

routes:
    pattern: /routes
    defaults: { _controller: DTLTrainerBundle:Route:index }

route_new:
    pattern: /route/new
    defaults: { _controller: DTLTrainerBundle:Route:new }

route_edit:
    pattern: /route/{route_id}/edit
    defaults: { _controller: DTLTrainerBundle:Route:edit }

route_view:
    pattern: /route/{route_id}
    defaults: { _controller: DTLTrainerBundle:Route:view }

route_new_session:
    pattern: /route/{route_id}/session/new
    defaults: { _controller: DTLTrainerBundle:Route:newSession }

filter_update:
    pattern: /filter/update
    defaults: { _controller: DTLTrainerBundle:Filter:update }
